machine:
  services:
    - docker

dependencies:
  override:
    - docker pull yukinying/chrome-headless-browser

test:
  override:
    - docker run --init -it --rm --name chrome --shm-size=1024m -p=127.0.0.1:9222:9222 --cap-add=SYS_ADMIN \
  yukinying/chrome-headless-browser
