version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Start headless Chrome in Docker and run tests
          command: |
            set -x
            echo "Hello World"
            docker run -d --rm --name chrome --shm-size=1024m -p=127.0.0.1:9222:9222 --cap-add=SYS_ADMIN yukinying/chrome-headless-browser
            yarn
            yarn test
