service: chromeless-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    DEBUG: "*"
    AWS_IOT_HOST: ${env:AWS_IOT_HOST}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iot:Connect"
        - "iot:Publish"
        - "iot:Subscribe"
        - "iot:Receive"
        - "iot:GetThingShadow"
        - "iot:UpdateThingShadow"
      Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline

package:
  exclude:
    # - ./**
    - node_modules/typescript/**
    - node_modules/serverless-**/**
    - node_modules/prettier**/**
    - node_modules/lighthouse**/**
    - node_modules/devtools-timeline-model/**
    - node_modules/chrome-devtools-frontend/**
    - node_modules/uglify-js/**
    - node_modules/chromeless/**
    - '!node_modules/chromeless/dist/**'
    - '!node_modules/chromeless/package.json'
  include:
    - ./src/**.js
    - node_modules/chromeless/dist/**
    - node_modules/chromeless/package.json

  excludeDevDependencies: false

functions:

  run:
    memorySize: 1536
    timeout: 300
    handler: src/run.run
    events:
      - iot:
          sql: "SELECT * FROM 'chrome/new-session'"

  version:
    memorySize: 128
    handler: src/version.default
    events:
    - http:
        path: /version
        method: get

  session:
    memorySize: 1536
    timeout: 300
    handler: src/session.run
    events:
      - http: OPTIONS /session
      - http:
          method: GET
          path: /session

  disconnect:
    memorySize: 128
    handler: src/disconnect.default
    timeout: 30
    events:
      - iot:
          sql: "SELECT * FROM 'chrome/last-will'"

resources:
  Resources:
    RunLogGroup:
      Properties:
        RetentionInDays: 7
    VersionLogGroup:
      Properties:
        RetentionInDays: 7
    SessionLogGroup:
      Properties:
        RetentionInDays: 7
    DisconnectLogGroup:
      Properties:
        RetentionInDays: 7
