service: chromeless-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  deploymentBucket: serverless-deployments-${env:AWS_REGION}-${env:AWS_ACCOUNT_ID}
  environment:
    DEBUG: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome

package:
  exclude:
    # - ./**
    - node_modules/typescript/**
    - node_modules/serverless-**/**
    - node_modules/prettier**/**
    - node_modules/lighthouse**/**
    - node_modules/devtools-timeline-model/**
    - node_modules/chrome-devtools-frontend/**
    - node_modules/uglify-js/**
  include:
    - ./src/**.js
  excludeDevDependencies: false

functions:

  run:
    memorySize: 1536
    timeout: 300
    handler: src/run.default

  version:
    memorySize: 128
    handler: src/version.default
    events:
    - http:
        path: /version
        method: get

resources:
  Resources:

    RunLogGroup:
      Properties:
        RetentionInDays: 7
    VersionLogGroup:
      Properties:
        RetentionInDays: 7
